from fastapi import FastAPI, Response, status, HTTPException, Depends, APIRouter
from sqlalchemy.orm import Session
from .. import models, schemas
from ..utils import hash_password
from ..database import engine, get_db

router = APIRouter(
    prefix="/users",
)

@router.post("/", status_code=status.HTTP_201_CREATED, response_model=schemas.UserOut)
def create_user(user: schemas.UserCreate, db: Session = Depends(get_db)):
    # confirm if user email already exists in the database
    existing_user = db.query(models.User).filter(models.User.email == user.email).first()
    if existing_user:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Email already registered")
    
    # hash the password before storing it in the database
    hashed_password = hash_password(user.password)
    user.password = hashed_password
    
    # create a new user instance and save it to the database
    new_user = models.User(**user.model_dump()) # unpack the user object into a dictionary and pass it to the User model to create a new instance of the User model
    db.add(new_user)
    db.commit()
    db.refresh(new_user) # refresh the instance to get the new data from the database, including the id that was generated by the database
    return new_user

@router.get("/", status_code=status.HTTP_200_OK, response_model=list[schemas.UserOut])
def get_users(db: Session = Depends(get_db)):
    users = db.query(models.User).all()
    return users

@router.get("/{id}", status_code=status.HTTP_200_OK, response_model=schemas.UserOut)
def get_user(id: int, db: Session = Depends(get_db)):
    user = db.query(models.User).filter(models.User.id == id).first()
    if not user:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                            detail=f"User with id: {id} does not exist")
    return user

