from fastapi import Body, FastAPI, Response, status, HTTPException, Depends
from sqlalchemy.orm import Session
from . import models, schemas
from .database import engine, get_db
from .utils import hash_password

models.Base.metadata.create_all(bind=engine) # create the tables in the database based on the models defined in models.py

app = FastAPI()

@app.get("/")
def root():
    return {"message": "Welcome to my API"}

@app.get("/posts", status_code=status.HTTP_200_OK, response_model=list[schemas.PostResponse])
def get_posts(db: Session = Depends(get_db)):
    posts = db.query(models.Post).all()
    return posts

@app.post("/posts", status_code=status.HTTP_201_CREATED, response_model=schemas.PostResponse)
def create_posts(post: schemas.PostCreate, db: Session = Depends(get_db)):
    new_post = models.Post(**post.model_dump()) # unpack the post object into a dictionary and pass it to the Post model to create a new instance of the Post model
    db.add(new_post)
    db.commit()
    db.refresh(new_post) # refresh the instance to get the new data from the database, including the id that was generated by the database
    return new_post

@app.get("/posts/latest", status_code=status.HTTP_200_OK, response_model=schemas.PostResponse)
def get_latest_post(db: Session = Depends(get_db)):
    # Order by ID descending and take the first one
    post = db.query(models.Post).order_by(models.Post.id.desc()).first()
    return post


@app.get("/posts/{id}", response_model=schemas.PostResponse, status_code=status.HTTP_200_OK)
def get_post(id: int, db: Session = Depends(get_db)):
    post = db.query(models.Post).filter(models.Post.id == id).first()
    if not post:
        # response.status_code = status.HTTP_404_NOT_FOUND
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                            detail=f"Post with id: {id} does not exist")
    return post

@app.delete("/posts/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_post(id: int, db: Session = Depends(get_db)):
    # Perform the delete and get the deleted row back in one go
    post = db.query(models.Post).filter(models.Post.id == id)
    if not post.first():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                            detail=f"Post with id: {id} does not exist")
    post.delete(synchronize_session=False)
    db.commit()
    # 204 No Content should not return a body
    return Response(status_code=status.HTTP_204_NO_CONTENT)

@app.patch("/posts/{id}", status_code=status.HTTP_200_OK, response_model=schemas.PostResponse)
def update_post_partial(id: int, post: schemas.PostPatch, db: Session = Depends(get_db)):
    # 1. Get the query object
    post_query = db.query(models.Post).filter(models.Post.id == id)
    existing_post = post_query.first()

    if not existing_post:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, 
                            detail=f"Post {id} not found")

    # 2. Extract only the provided fields
    update_data = post.model_dump(exclude_unset=True)

    if not update_data:
        raise HTTPException(status_code=400, detail="No fields provided for update")

    # 3. Update using the dictionary directly
    post_query.update(update_data, synchronize_session=False)
    db.commit()

    return post_query.first()

@app.put("/posts/{id}", status_code=status.HTTP_200_OK, response_model=schemas.PostResponse)
def update_post(id: int, post: schemas.PostCreate, db: Session = Depends(get_db)): # ensure that the request comes with the right data structure by using the Post model
    post_query = db.query(models.Post).filter(models.Post.id == id)
    if not post_query.first():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                            detail=f"Post with id: {id} does not exist")
    post_query.update(post.model_dump(), synchronize_session=False)
    db.commit()
    return post_query.first()


@app.post("/users", status_code=status.HTTP_201_CREATED, response_model=schemas.UserOut)
def create_user(user: schemas.UserCreate, db: Session = Depends(get_db)):
    # confirm if user email already exists in the database
    existing_user = db.query(models.User).filter(models.User.email == user.email).first()
    if existing_user:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail="Email already registered")
    
    # hash the password before storing it in the database
    hashed_password = hash_password(user.password)
    user.password = hashed_password
    
    # create a new user instance and save it to the database
    new_user = models.User(**user.model_dump()) # unpack the user object into a dictionary and pass it to the User model to create a new instance of the User model
    db.add(new_user)
    db.commit()
    db.refresh(new_user) # refresh the instance to get the new data from the database, including the id that was generated by the database
    return new_user

@app.get("/users/{id}", status_code=status.HTTP_200_OK, response_model=schemas.UserOut)
def get_user(id: int, db: Session = Depends(get_db)):
    user = db.query(models.User).filter(models.User.id == id).first()
    if not user:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                            detail=f"User with id: {id} does not exist")
    return user

