from time import sleep
from typing import Optional
from random import randrange
from fastapi import Body, FastAPI, Response, status, HTTPException, Depends
import psycopg2
from psycopg2.extras import RealDictCursor
from pydantic import BaseModel
from sqlalchemy.orm import Session
from . import models
from .database import engine, get_db

models.Base.metadata.create_all(bind=engine) # create the tables in the database based on the models defined in models.py

app = FastAPI()

# Pydantic models are used to define the structure of the data that we expect to receive in our API.
# They also provide validation and serialization of the data. In this example, we define a Post model with three fields: title, content, and published.
# The published field has a default value of True.
class Post(BaseModel):
    title: str
    content: str
    published: bool = True
    # rating: Optional[int] = None
    
class PostPatch(BaseModel):
    title: Optional[str] = None
    content: Optional[str] = None

# while True:
#     try:
#         conn = psycopg2.connect(host='localhost', database='fastapi',
#                                 user='postgres', password='root', cursor_factory=RealDictCursor)
#         cursor = conn.cursor()
#         print("Database connection successful")
#         break
#     except Exception as e:
#         print("Database connection failed")
#         print("Error: " + str(e))
#         sleep(2)

# my_posts = [{"title": "title of post 1", "content": "content of post 1", "id": 1, "published": True, "rating": 5},
#             {"title": "favorite foods", "content": "I like pizza", "id": 2, "published": True, "rating": 10}]

# def find_post(id):
#     for post in my_posts:
#         if post["id"] == id:
#             return post

@app.get("/")
def root():
    return {"message": "Welcome to my API"}

# test
@app.get("/sqlalchemy")
def test_post(db: Session = Depends(get_db)):
    
    posts = db.query(models.Post).all()
    return {"data": posts}

@app.get("/posts")
def get_posts(db: Session = Depends(get_db)):
    posts = db.query(models.Post).all()
    return {"data": posts}

@app.post("/posts", status_code=status.HTTP_201_CREATED)
def create_posts(post: Post, db: Session = Depends(get_db)):
    new_post = models.Post(**post.model_dump()) # unpack the post object into a dictionary and pass it to the Post model to create a new instance of the Post model
    db.add(new_post)
    db.commit()
    db.refresh(new_post) # refresh the instance to get the new data from the database, including the id that was generated by the database
    return {"data": new_post, "UserMessage": "Post created successfully"}

@app.get("/posts/latest")
def get_latest_post(db: Session = Depends(get_db)):
    # Order by ID descending and take the first one
    post = db.query(models.Post).order_by(models.Post.id.desc()).first()
    return {"data": post}


@app.get("/posts/{id}")
def get_post(id: int, db: Session = Depends(get_db)):
    post = db.query(models.Post).filter(models.Post.id == id).first()
    if not post:
        # response.status_code = status.HTTP_404_NOT_FOUND
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                            detail=f"Post with id: {id} does not exist")
    return {"post_detail": post}

@app.delete("/posts/{id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_post(id: int, db: Session = Depends(get_db)):
    # Perform the delete and get the deleted row back in one go
    post = db.query(models.Post).filter(models.Post.id == id)
    if not post.first():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                            detail=f"Post with id: {id} does not exist")
    post.delete(synchronize_session=False)
    db.commit()
    # 204 No Content should not return a body
    return Response(status_code=status.HTTP_204_NO_CONTENT)

@app.patch("/posts/{id}")
def update_post_partial(id: int, post: PostPatch, db: Session = Depends(get_db)):
    # 1. Get the query object
    post_query = db.query(models.Post).filter(models.Post.id == id)
    existing_post = post_query.first()

    if not existing_post:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, 
                            detail=f"Post {id} not found")

    # 2. Extract only the provided fields
    update_data = post.model_dump(exclude_unset=True)

    if not update_data:
        raise HTTPException(status_code=400, detail="No fields provided for update")

    # 3. Update using the dictionary directly
    post_query.update(update_data, synchronize_session=False)
    db.commit()

    return {"data": post_query.first(), "UserMessage": "Post updated successfully"}

@app.put("/posts/{id}", status_code=status.HTTP_200_OK)
def update_post(id: int, post: Post, db: Session = Depends(get_db)): # ensure that the request comes with the right data structure by using the Post model
    post_query = db.query(models.Post).filter(models.Post.id == id)
    if not post_query.first():
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND,
                            detail=f"Post with id: {id} does not exist")
    post_query.update(post.model_dump(), synchronize_session=False)
    db.commit()
    return {"data": post_query.first(), "UserMessage": "Post updated successfully"}
